server:
  port: 7777
spring:
  application:
    name: quartz-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tan960618
    url: jdbc:mysql://127.0.0.1:3306/Quartz
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
#      这个地方auto-commit必须设置成true 否则commit会回滚
      auto-commit: true
      connection-timeout: 2000
      pool-name: hikari-pool
      max-lifetime: 20000
      connection-test-query: SELECT 1
      idle-timeout: 10000
    type: com.zaxxer.hikari.HikariDataSource

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.example.quartz
  protocol:
    port: 20881
    name: dubbo
logging:
  level:
    com: debug
    org.quartz: error
